lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser # Use the default browser stack

    resources "/coins", CoinController, only: [:index] do
      resources "/prices", PriceController, only: [:index]
    end

    get "/", CoinController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end
end

lib/mix/tasks/crypto.write_price.ex
defmodule Mix.Tasks.Crypto.WritePrice do
  use Mix.Task
  alias Teacher.{Repo, Crypto}

  @shortdoc "Fetches the current price of a cryptocurrency and saves it"
  @moduledoc """
    Fetches the current price of a cryptocurrency and saves it.

      mix crypto.write_price

  ## Examples

      To save the current price of a Bitcoin

        mix crypto.write_price btc

      You can also save the price for many coins at once

        mix crypto.write_price eth btc
  """

  def run(args) do
    Mix.Ecto.ensure_started(Repo, [])
    Application.ensure_all_started(:httpoison)

    for api_id <- args do
      coin = Crypto.coin_by_api_id!(api_id)
      Crypto.write_price(coin.id)
    end
  end

end

lib/teacher/application.ex
defmodule Teacher.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Teacher.Repo, []),
      # Start the endpoint when the application starts
      supervisor(TeacherWeb.Endpoint, []),
      # Start your own worker by calling: Teacher.Worker.start_link(arg1, arg2, arg3)
      # worker(Teacher.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Teacher.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TeacherWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/teacher/crypto/coin.ex
defmodule Teacher.Crypto.Coin do
  use Ecto.Schema
  import Ecto.Changeset
  alias Teacher.Crypto.Price

  schema "coins" do
    field :name, :string
    field :api_id, :string
    has_many :prices, Teacher.Crypto.Price

    timestamps()
  end

  @doc false
  def changeset(coin, attrs) do
    coin
    |> cast(attrs, [:name, :api_id])
    |> validate_required([:name, :api_id])
  end
end

lib/teacher/crypto/coin_data.ex
defmodule Teacher.Crypto.CoinData  do

  def fetch_price(id) do
    id
    |> String.upcase()
    |> url()
    |> HTTPoison.get!()
    |> Map.get(:body)
    |> Jason.decode!()
    |> Map.get("price")
  end

  defp url(id) do
    "http://coincap.io/page/" <> id
  end

end

lib/teacher/crypto/crypto.ex
defmodule Teacher.Crypto do
  @moduledoc """
  The Crypto context.
  """

  import Ecto.Query, warn: false
  alias Teacher.Repo

  alias Teacher.Crypto.{Coin, Price}
  alias Teacher.Crypto.CoinData

  def write_price(id) do
    coin = get_coin!(id)
    price = CoinData.fetch_price(coin.api_id)

    coin
    |> Ecto.build_assoc(:prices, %{price: price})
    |> Repo.insert()
  end

  @doc """
  Returns the list of coins.

  ## Examples

      iex> list_coins()
      [%Coin{}, ...]

  """
  def list_coins do
    Repo.all(Coin)
  end

  @doc """
  Gets a single coin.

  Raises `Ecto.NoResultsError` if the Coin does not exist.

  ## Examples

      iex> get_coin!(123)
      %Coin{}

      iex> get_coin!(456)
      ** (Ecto.NoResultsError)

  """
  def get_coin!(id) do
    Coin
    |> Repo.get!(id)
    |> Repo.preload([prices: (from price in Price, order_by: [desc: price.inserted_at])])
  end

  def coin_by_api_id!(api_id) do
    Coin
    |> Repo.get_by!(api_id: api_id)
  end

  @doc """
  Creates a coin.

  ## Examples

      iex> create_coin(%{field: value})
      {:ok, %Coin{}}

      iex> create_coin(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_coin(attrs \\ %{}) do
    %Coin{}
    |> Coin.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a coin.

  ## Examples

      iex> update_coin(coin, %{field: new_value})
      {:ok, %Coin{}}

      iex> update_coin(coin, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_coin(%Coin{} = coin, attrs) do
    coin
    |> Coin.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Coin.

  ## Examples

      iex> delete_coin(coin)
      {:ok, %Coin{}}

      iex> delete_coin(coin)
      {:error, %Ecto.Changeset{}}

  """
  def delete_coin(%Coin{} = coin) do
    Repo.delete(coin)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking coin changes.

  ## Examples

      iex> change_coin(coin)
      %Ecto.Changeset{source: %Coin{}}

  """
  def change_coin(%Coin{} = coin) do
    Coin.changeset(coin, %{})
  end
end

lib/teacher/crypto/price.ex
defmodule Teacher.Crypto.Price do
  use Ecto.Schema
  import Ecto.Changeset
  alias Teacher.Crypto.Coin

  schema "prices" do
    field :price, :float
    belongs_to :coin, Coin

    timestamps()
  end

  @doc false
  def changeset(price, attrs) do
    price
    |> cast(attrs, [:price])
    |> validate_required([:price])
  end
end

lib/teacher/repo.ex
defmodule Teacher.Repo do
  use Ecto.Repo, otp_app: :teacher

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/teacher_web/controllers/coin_controller.ex
defmodule TeacherWeb.CoinController do
  use TeacherWeb, :controller

  alias Teacher.Crypto

  def index(conn, _params) do
    coins = Crypto.list_coins()
    render(conn, "index.html", coins: coins)
  end

end

lib/teacher_web/controllers/page_controller.ex
defmodule TeacherWeb.PageController do
  use TeacherWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/teacher_web/controllers/price_controller.ex
defmodule TeacherWeb.PriceController do
  use TeacherWeb, :controller

  alias Teacher.Crypto

  def index(conn, %{"coin_id" => coin_id}) do
    coin = Crypto.get_coin!(coin_id)
    render(conn, "index.html", coin: coin, prices: coin.prices)
  end

end

lib/teacher_web/views/coin_view.ex
defmodule TeacherWeb.CoinView do
  use TeacherWeb, :view
end

lib/teacher_web/views/error_view.ex
defmodule TeacherWeb.ErrorView do
  use TeacherWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/teacher_web/views/layout_view.ex
defmodule TeacherWeb.LayoutView do
  use TeacherWeb, :view
end

lib/teacher_web/views/page_view.ex
defmodule TeacherWeb.PageView do
  use TeacherWeb, :view
end

lib/teacher_web/views/price_view.ex
defmodule TeacherWeb.PriceView do
  use TeacherWeb, :view

  def format_inserted_at(%{year: year, month: month, day: day, hour: hour, minute: minute, second: second}) do
    "#{month}-#{day}-#{year} #{hour}:#{minute}:#{second}"
  end
end

lib/teacher_web/templates/coin/index.html.eex
<h2>Cryptocurrency Coins</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for coin <- @coins do %>
      <tr>
        <td><%= coin.name %></td>
        <td><%= link "Price history", to: coin_price_path(@conn, :index, coin) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

lib/teacher_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Teacher!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= link "Home", to: "/" %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/teacher_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/teacher_web/templates/price/index.html.eex
<h2><%= @coin.name %> Price History</h2>

<table class="table">
  <thead>
    <tr>
      <th>Price</th>
      <th>Recorded</th>
    </tr>
  </thead>
  <tbody>
  <%= for price <- @prices do %>
      <tr>
        <td>&#36;<%= Float.round(price.price, 2) %></td>
        <td><%= format_inserted_at(price.inserted_at) %></td>
      </tr>
  <% end %>
  </tbody>
</table>